# Generated by Django 4.2.4 on 2023-08-30 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
